=== PascalBrouwers/catalog-storefront/app/code/Magento/CatalogProduct/etc/storage.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
/**
 * Schema for DI configuration
 *
 * Copyright Â© Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="config">
        <xs:annotation>
            <xs:documentation>
                The config file to work with data storage. Such as connection options, timeout, default configurations that need to be applied on storage.
            </xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:choice maxOccurs="unbounded">
                <xs:element name="connections" type="connections" minOccurs="1" maxOccurs="1" />
                <xs:element name="timeout" type="xs:integer" minOccurs="1" maxOccurs="1">
                    <xs:annotation>
                        <xs:documentation>
                            Timeout in seconds for response from remote storage service.
                        </xs:documentation>
                    </xs:annotation>
                </xs:element>
            </xs:choice>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="connections">
        <xs:annotation>
            <xs:documentation>
                List of connections and options to those connections.
            </xs:documentation>
        </xs:annotation>
        <xs:choice maxOccurs="unbounded">
            <xs:element name="item" type="itemConnection" minOccurs="1" maxOccurs="unbounded" />
        </xs:choice>
    </xs:complexType>

    <xs:complexType name="itemConnection">
        <xs:annotation>
            <xs:documentation>
                Connection item with options to be able to connect to remote storage service.
            </xs:documentation>
        </xs:annotation>
        <xs:choice maxOccurs="unbounded">
            <xs:element name="protocol" type="xs:string" minOccurs="1" maxOccurs="1" />
            <xs:element name="hostname" type="xs:string" minOccurs="1" maxOccurs="1" />
            <xs:element name="port" type="xs:integer" minOccurs="1" maxOccurs="1" />
            <xs:element name="username" type="xs:string" minOccurs="0" maxOccurs="1" />
            <xs:element name="password" type="xs:string" minOccurs="0" maxOccurs="1" />
            <xs:element name="timeout" type="xs:integer" minOccurs="1" maxOccurs="1">
                <xs:annotation>
                    <xs:documentation>
                        Timeout in seconds to achieve connection for remote storage service.
                    </xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="alias_name" type="xs:string" minOccurs="0" maxOccurs="1">
                <xs:annotation>
                    <xs:documentation>
                        Alias name to access data of source on remote storage service.
                    </xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="alias_name" type="xs:string" minOccurs="0" maxOccurs="1">
                <xs:annotation>
                    <xs:documentation>
                        Alias name to access data of source on remote storage service.
                    </xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="source_prefix" type="xs:string" minOccurs="0" maxOccurs="1">
                <xs:annotation>
                    <xs:documentation>
                        Prefix of source on remote storage service.
                    </xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="source_current_version" type="xs:string" minOccurs="0" maxOccurs="1">
                <xs:annotation>
                    <xs:documentation>
                        Current version of source on remote storage service.
                    </xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:choice>
        <xs:attribute name="name" type="xs:string" use="required"/>
    </xs:complexType>

</xs:schema>

=== PascalBrouwers/catalog-storefront/app/code/Magento/CatalogProduct/etc/storage.xml
<?xml version="1.0"?>
<!--
/**
* Copyright Â© Magento, Inc. All rights reserved.
* See COPYING.txt for license details.
*/
-->
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="storage.xsd">
    <!--
        Desired structure that has to be hardcoded to app/etc/env.php under the 'catalog-store-front' key
        until Catalog Store front application still be the part of Magento monolith.
    -->
    <connections>
        <item name="default">
            <protocol>http</protocol>
            <hostname>localhost</hostname>
            <port>9200</port>
            <username />
            <password />
            <timeout>3</timeout>
        </item>
    </connections>
    <timeout>60</timeout>
    <alias_name>catalog_storefront</alias_name>
    <source_prefix>catalog_storefront_v</source_prefix>
    <source_current_version>1</source_current_version>
</config>
